
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Label label1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Entry pantalla;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Button vaciar;

	private global::Gtk.Button borrar;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Button boton7;

	private global::Gtk.Button boton8;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Button boton9;

	private global::Gtk.Button dividir;

	private global::Gtk.VBox vbox3;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Button boton4;

	private global::Gtk.Button boton5;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Button boton6;

	private global::Gtk.Button multiplicar;

	private global::Gtk.HBox hbox6;

	private global::Gtk.Button boton1;

	private global::Gtk.Button boton2;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Button boton3;

	private global::Gtk.Button restar;

	private global::Gtk.HBox hbox8;

	private global::Gtk.Button coma;

	private global::Gtk.Button boton;

	private global::Gtk.HBox hbox10;

	private global::Gtk.Button igual;

	private global::Gtk.Button sumar;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("CALCULADORA");
		this.vbox1.Add(this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.pantalla = new global::Gtk.Entry();
		this.pantalla.CanFocus = true;
		this.pantalla.Name = "pantalla";
		this.pantalla.IsEditable = false;
		this.pantalla.InvisibleChar = '•';
		this.vbox2.Add(this.pantalla);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.pantalla]));
		w2.Position = 0;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vaciar = new global::Gtk.Button();
		this.vaciar.WidthRequest = 160;
		this.vaciar.CanFocus = true;
		this.vaciar.Name = "vaciar";
		this.vaciar.UseUnderline = true;
		this.vaciar.Label = global::Mono.Unix.Catalog.GetString("VACIAR");
		this.hbox1.Add(this.vaciar);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vaciar]));
		w3.Position = 0;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.borrar = new global::Gtk.Button();
		this.borrar.WidthRequest = 160;
		this.borrar.CanFocus = true;
		this.borrar.Name = "borrar";
		this.borrar.UseUnderline = true;
		this.borrar.Label = global::Mono.Unix.Catalog.GetString("BORRAR");
		this.hbox1.Add(this.borrar);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.borrar]));
		w4.Position = 1;
		w4.Fill = false;
		this.vbox2.Add(this.hbox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.boton7 = new global::Gtk.Button();
		this.boton7.WidthRequest = 85;
		this.boton7.HeightRequest = 50;
		this.boton7.CanFocus = true;
		this.boton7.Name = "boton7";
		this.boton7.UseUnderline = true;
		this.boton7.Label = global::Mono.Unix.Catalog.GetString("7");
		this.hbox2.Add(this.boton7);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.boton7]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.boton8 = new global::Gtk.Button();
		this.boton8.WidthRequest = 85;
		this.boton8.CanFocus = true;
		this.boton8.Name = "boton8";
		this.boton8.UseUnderline = true;
		this.boton8.Label = global::Mono.Unix.Catalog.GetString("8");
		this.hbox2.Add(this.boton8);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.boton8]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.boton9 = new global::Gtk.Button();
		this.boton9.WidthRequest = 85;
		this.boton9.CanFocus = true;
		this.boton9.Name = "boton9";
		this.boton9.UseUnderline = true;
		this.boton9.Label = global::Mono.Unix.Catalog.GetString("9");
		this.hbox3.Add(this.boton9);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.boton9]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.dividir = new global::Gtk.Button();
		this.dividir.WidthRequest = 100;
		this.dividir.CanFocus = true;
		this.dividir.Name = "dividir";
		this.dividir.UseUnderline = true;
		this.dividir.Label = global::Mono.Unix.Catalog.GetString("/");
		this.hbox3.Add(this.dividir);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.dividir]));
		w9.Position = 1;
		w9.Expand = false;
		this.hbox2.Add(this.hbox3);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.hbox3]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox2.Add(this.hbox2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
		w11.Position = 2;
		this.vbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.boton4 = new global::Gtk.Button();
		this.boton4.WidthRequest = 85;
		this.boton4.HeightRequest = 50;
		this.boton4.CanFocus = true;
		this.boton4.Name = "boton4";
		this.boton4.UseUnderline = true;
		this.boton4.Label = global::Mono.Unix.Catalog.GetString("4");
		this.hbox4.Add(this.boton4);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.boton4]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.boton5 = new global::Gtk.Button();
		this.boton5.WidthRequest = 85;
		this.boton5.CanFocus = true;
		this.boton5.Name = "boton5";
		this.boton5.UseUnderline = true;
		this.boton5.Label = global::Mono.Unix.Catalog.GetString("5");
		this.hbox4.Add(this.boton5);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.boton5]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.boton6 = new global::Gtk.Button();
		this.boton6.WidthRequest = 85;
		this.boton6.CanFocus = true;
		this.boton6.Name = "boton6";
		this.boton6.UseUnderline = true;
		this.boton6.Label = global::Mono.Unix.Catalog.GetString("6");
		this.hbox5.Add(this.boton6);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.boton6]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.multiplicar = new global::Gtk.Button();
		this.multiplicar.WidthRequest = 100;
		this.multiplicar.CanFocus = true;
		this.multiplicar.Name = "multiplicar";
		this.multiplicar.UseUnderline = true;
		this.multiplicar.Label = global::Mono.Unix.Catalog.GetString("x");
		this.hbox5.Add(this.multiplicar);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.multiplicar]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		this.hbox4.Add(this.hbox5);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.hbox5]));
		w17.Position = 2;
		w17.Expand = false;
		w17.Fill = false;
		this.vbox3.Add(this.hbox4);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox4]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.boton1 = new global::Gtk.Button();
		this.boton1.WidthRequest = 85;
		this.boton1.HeightRequest = 50;
		this.boton1.CanFocus = true;
		this.boton1.Name = "boton1";
		this.boton1.UseUnderline = true;
		this.boton1.Label = global::Mono.Unix.Catalog.GetString("1");
		this.hbox6.Add(this.boton1);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.boton1]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.boton2 = new global::Gtk.Button();
		this.boton2.WidthRequest = 85;
		this.boton2.CanFocus = true;
		this.boton2.Name = "boton2";
		this.boton2.UseUnderline = true;
		this.boton2.Label = global::Mono.Unix.Catalog.GetString("2");
		this.hbox6.Add(this.boton2);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.boton2]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.boton3 = new global::Gtk.Button();
		this.boton3.WidthRequest = 85;
		this.boton3.CanFocus = true;
		this.boton3.Name = "boton3";
		this.boton3.UseUnderline = true;
		this.boton3.Label = global::Mono.Unix.Catalog.GetString("3");
		this.hbox7.Add(this.boton3);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.boton3]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.restar = new global::Gtk.Button();
		this.restar.WidthRequest = 100;
		this.restar.CanFocus = true;
		this.restar.Name = "restar";
		this.restar.UseUnderline = true;
		this.restar.Label = global::Mono.Unix.Catalog.GetString("-");
		this.hbox7.Add(this.restar);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.restar]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		this.hbox6.Add(this.hbox7);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.hbox7]));
		w23.Position = 2;
		w23.Expand = false;
		w23.Fill = false;
		this.vbox3.Add(this.hbox6);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox6]));
		w24.Position = 1;
		w24.Expand = false;
		w24.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.coma = new global::Gtk.Button();
		this.coma.WidthRequest = 85;
		this.coma.HeightRequest = 50;
		this.coma.CanFocus = true;
		this.coma.Name = "coma";
		this.coma.UseUnderline = true;
		this.coma.Label = global::Mono.Unix.Catalog.GetString(".");
		this.hbox8.Add(this.coma);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.coma]));
		w25.Position = 0;
		w25.Expand = false;
		w25.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.boton = new global::Gtk.Button();
		this.boton.WidthRequest = 85;
		this.boton.CanFocus = true;
		this.boton.Name = "boton";
		this.boton.UseUnderline = true;
		this.boton.Label = global::Mono.Unix.Catalog.GetString("0");
		this.hbox8.Add(this.boton);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.boton]));
		w26.Position = 1;
		w26.Expand = false;
		w26.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.igual = new global::Gtk.Button();
		this.igual.WidthRequest = 85;
		this.igual.CanFocus = true;
		this.igual.Name = "igual";
		this.igual.UseUnderline = true;
		this.igual.Label = global::Mono.Unix.Catalog.GetString("=");
		this.hbox10.Add(this.igual);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.igual]));
		w27.Position = 0;
		w27.Expand = false;
		w27.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.sumar = new global::Gtk.Button();
		this.sumar.WidthRequest = 100;
		this.sumar.CanFocus = true;
		this.sumar.Name = "sumar";
		this.sumar.UseUnderline = true;
		this.sumar.Label = global::Mono.Unix.Catalog.GetString("+");
		this.hbox10.Add(this.sumar);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.sumar]));
		w28.Position = 1;
		w28.Expand = false;
		w28.Fill = false;
		this.hbox8.Add(this.hbox10);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.hbox10]));
		w29.Position = 2;
		w29.Expand = false;
		w29.Fill = false;
		this.vbox3.Add(this.hbox8);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox8]));
		w30.Position = 2;
		w30.Expand = false;
		w30.Fill = false;
		this.vbox1.Add(this.vbox3);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox3]));
		w31.Position = 2;
		w31.Expand = false;
		w31.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 389;
		this.DefaultHeight = 317;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.vaciar.Clicked += new global::System.EventHandler(this.OnVaciarClicked);
		this.borrar.Clicked += new global::System.EventHandler(this.OnBorrarClicked);
		this.boton7.Clicked += new global::System.EventHandler(this.OnBoton7Clicked);
		this.boton8.Clicked += new global::System.EventHandler(this.OnBoton8Clicked);
		this.boton9.Clicked += new global::System.EventHandler(this.OnBoton9Clicked);
		this.dividir.Clicked += new global::System.EventHandler(this.OnDividirClicked);
		this.boton4.Clicked += new global::System.EventHandler(this.OnBoton4Clicked);
		this.boton5.Clicked += new global::System.EventHandler(this.OnBoton5Clicked);
		this.boton6.Clicked += new global::System.EventHandler(this.OnBoton6Clicked);
		this.multiplicar.Clicked += new global::System.EventHandler(this.OnMultiplicarClicked);
		this.boton1.Clicked += new global::System.EventHandler(this.OnBoton1Clicked);
		this.boton2.Clicked += new global::System.EventHandler(this.OnBoton2Clicked);
		this.boton3.Clicked += new global::System.EventHandler(this.OnBoton3Clicked);
		this.restar.Clicked += new global::System.EventHandler(this.OnRestarClicked);
		this.coma.Clicked += new global::System.EventHandler(this.OnComaClicked);
		this.boton.Clicked += new global::System.EventHandler(this.OnBotonClicked);
		this.igual.Clicked += new global::System.EventHandler(this.OnIgualClicked);
		this.sumar.Clicked += new global::System.EventHandler(this.OnSumarClicked);
	}
}
